### ISSUE TITLE
Erro ao executar encrypt-card-data

### ISSUE THREAD

**Issue by ferranti-sensedia** [Fconstant/elo-api-jose#2]
Caso o usuário execute o **encrypt-card-data** sem configurar o **client_id** é gerado o server.json com a seguinte mensagem 

`{
        "error": "Could not find a required APP in the request, identified by HEADER client_id."
}`
e retorna o erro  abaixo:
`(node:15519) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'kty' of undefined`

Posteriormente, mesmo configurando o **client_id** corretamente continua retornando o mesmo erro acima pois não é gerado novamente o **server.json**. Para que a execução funcione é necessário apagar o server.json e executar novamente o **encrypt-card-data**.

**Comment by Fconstant** [comment]
Corrigido em 0d40cf211f7ba2051eae9047105e26324942b159
